version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: inomad_khural_db
    restart: always
    environment:
      POSTGRES_USER: inomad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inomad_khural
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
