[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
